### ISSUE TITLE
[FEATURE] Implement InsertLine method in AsBroadcastScript.cs

### ISSUE THREAD

**Issue by RasmusBroborg** [RasmusBroborg/PostProductionScript#11]
**Describe the solution you'd like**
The method should insert a line on a specific position in the list of lines. All other lines should change their line numbers if the inserted line affects their position.

**Comment by EvgenyPribytkov** [comment]
I want to be assigned to issue.

**Comment by RasmusBroborg** [comment]
Fix in #12
