### ISSUE TITLE
[FEATURE] Add properties to ScriptLine.cs

### ISSUE THREAD

**Issue by RasmusBroborg** [RasmusBroborg/PostProductionScript#7]
**Describe the solution you'd like**
- Create properties for Source, Dialogue, Burned-in-subtitles, On-screen-text, Annotations
- Remove Body

**Additional context**
Reference file 
https://docs.google.com/spreadsheets/d/1UGgs5fVnO8T17kVZNkzrI2O4AyTSu3QC/edit#gid=320293518

**Comment by EvgenyPribytkov** [comment]
I want to be assigned to issue.
